name: 'Hello World Dotnet Action'
description: 'Test dotnet based action'
author: 'sbaker'
inputs:
  who:
    required: true
    description: 'Hello who?'
    default: 'World!'
runs:
  using: 'node12'
  main: 'index.js'
